site_name: Collector Docs

theme:
    name: material

nav:
    - Getting Started:
      - Getting started: index.md
      - Android: android.md
      - iOS: ios.md
    - Android:
      - Android manifest permissions and usage: manifest.md
      - Play Integrity Integration: android_play_integrity.md 
    - iOS:
      - Advanced setup: ios_advanced.md
    - Capacitor plugin: capacitor.md
    - Changelog:
      - Android Changelog: android_changelog.md
      - iOS Changelog: ios_changelog.md

